### PR TITLE
Test unwind features

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@serge-sans-paille it is good to be reviewed.
13 & 14 fail because of
```

Failed Tests (2):
  LLVM regression suite :: lto_and_cfi.c
  LLVM regression suite :: thinlto.c
```

(unrelated)

**Comment by serge-sans-paille** [comment]
ok looks like compatibility with default headers is not great, you can XFAIL this test on Fedora, I'll do the required upstream work to make it work.

**Comment by sylvestre** [comment]
Cool, one of the goal of this project: bring fedora and debian at the same level

**Comment by serge-sans-paille** [comment]
cc @sylvestre : Fedora f37 has been updated, the test now passes on all supported distrib, but it requires a rebase + a big squash :-)

**Comment by sylvestre** [comment]
I just restarted the CI jobs

**Pull request merged**
